package dao;

import java.util.List;
import model.HwStudent;
import model.HwStudentExample;
import org.apache.ibatis.annotations.Param;

public interface HwStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hw_student
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    int countByExample(HwStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hw_student
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    int deleteByExample(HwStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hw_student
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    int insert(HwStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hw_student
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    int insertSelective(HwStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hw_student
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    List<HwStudent> selectByExample(HwStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hw_student
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") HwStudent record, @Param("example") HwStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hw_student
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    int updateByExample(@Param("record") HwStudent record, @Param("example") HwStudentExample example);
}