package dao;

import java.util.List;
import model.Mark;
import model.MarkExample;
import org.apache.ibatis.annotations.Param;

public interface MarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    int countByExample(MarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    int deleteByExample(MarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    int insert(Mark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    int insertSelective(Mark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    List<Mark> selectByExample(MarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    Mark selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") Mark record, @Param("example") MarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    int updateByExample(@Param("record") Mark record, @Param("example") MarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    int updateByPrimaryKeySelective(Mark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    int updateByPrimaryKey(Mark record);
}