package dao;

import java.util.List;

import entity.TeacherMark;
import model.Student;
import model.Teacher;
import model.TeacherStudent;
import model.TeacherStudentExample;
import org.apache.ibatis.annotations.Param;

public interface TeacherStudentMapper {

    List<TeacherStudent> getTeacherMark(@Param("t")int t,@Param("s") int s);

    List<Teacher> queryStudentTeacher(int studentId);


    List<Student> queryTeacherStudent(int teacherId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student
     *
     * @mbggenerated Sun Jan 06 23:12:26 CST 2019
     */
    int countByExample(TeacherStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student
     *
     * @mbggenerated Sun Jan 06 23:12:26 CST 2019
     */
    int deleteByExample(TeacherStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student
     *
     * @mbggenerated Sun Jan 06 23:12:26 CST 2019
     */
    int insert(TeacherStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student
     *
     * @mbggenerated Sun Jan 06 23:12:26 CST 2019
     */
    int insertSelective(TeacherStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student
     *
     * @mbggenerated Sun Jan 06 23:12:26 CST 2019
     */
    List<TeacherStudent> selectByExample(TeacherStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student
     *
     * @mbggenerated Sun Jan 06 23:12:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") TeacherStudent record, @Param("example") TeacherStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student
     *
     * @mbggenerated Sun Jan 06 23:12:26 CST 2019
     */
    int updateByExample(@Param("record") TeacherStudent record, @Param("example") TeacherStudentExample example);
}