package model;

import java.util.Date;

public class Homework {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.id
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.teacher_id
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.catalog
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    private String catalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.begin_time
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.end_time
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.description
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.id
     *
     * @return the value of homework.id
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.id
     *
     * @param id the value for homework.id
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.teacher_id
     *
     * @return the value of homework.teacher_id
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.teacher_id
     *
     * @param teacherId the value for homework.teacher_id
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.catalog
     *
     * @return the value of homework.catalog
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.catalog
     *
     * @param catalog the value for homework.catalog
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog == null ? null : catalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.begin_time
     *
     * @return the value of homework.begin_time
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.begin_time
     *
     * @param beginTime the value for homework.begin_time
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.end_time
     *
     * @return the value of homework.end_time
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.end_time
     *
     * @param endTime the value for homework.end_time
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.description
     *
     * @return the value of homework.description
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.description
     *
     * @param description the value for homework.description
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}