package model;

public class HwStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hw_student.student_id
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hw_student.hw_id
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    private Integer hwId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hw_student.statue
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    private Byte statue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hw_student.student_id
     *
     * @return the value of hw_student.student_id
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hw_student.student_id
     *
     * @param studentId the value for hw_student.student_id
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hw_student.hw_id
     *
     * @return the value of hw_student.hw_id
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public Integer getHwId() {
        return hwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hw_student.hw_id
     *
     * @param hwId the value for hw_student.hw_id
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public void setHwId(Integer hwId) {
        this.hwId = hwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hw_student.statue
     *
     * @return the value of hw_student.statue
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public Byte getStatue() {
        return statue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hw_student.statue
     *
     * @param statue the value for hw_student.statue
     *
     * @mbggenerated Sun Jan 06 20:44:49 CST 2019
     */
    public void setStatue(Byte statue) {
        this.statue = statue;
    }
}