package model;

public class Mark {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.id
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.homework_id
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    private Integer homeworkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.student_id
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.id
     *
     * @return the value of mark.id
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.id
     *
     * @param id the value for mark.id
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.homework_id
     *
     * @return the value of mark.homework_id
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    public Integer getHomeworkId() {
        return homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.homework_id
     *
     * @param homeworkId the value for mark.homework_id
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    public void setHomeworkId(Integer homeworkId) {
        this.homeworkId = homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.mark
     *
     * @return the value of mark.mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.mark
     *
     * @param mark the value for mark.mark
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.student_id
     *
     * @return the value of mark.student_id
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.student_id
     *
     * @param studentId the value for mark.student_id
     *
     * @mbggenerated Sun Jan 06 22:44:20 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}